name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests lxml

      - name: Run stats updater
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: gokul-369
        run: python today.py

      - name: Commit changes
        run: |
          git config --global user.name "gokul-369"
          git config --global user.email "gokul369@outlook.com"

          git add dark_mode.svg light_mode.svg

          git commit -m "auto update github stats" || echo "No changes"

          git push